Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: Copyright (c) 2013, Hideyuki Tanaka
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  port: 80
  approot: "http://icfpc2013-clone.cloudapp.net"
  <<: *defaults
