Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://192.168.85.130:3000"
  copyright: Copyright (c) 2013, Hideyuki Tanaka
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
